### ISSUE TITLE
Package not available in CRAN

### ISSUE THREAD

**Issue by laxmipravn** [n8thangreen/CEdecisiontree#7]
Tried to install multiple times using the command: 
install_github("Health-Economics-in-R/CEdecisiontree")

But gave error, error is attached.
<img width="576" alt="Error" src="https://user-images.githubusercontent.com/93520388/139657450-3e561ddb-1197-479f-bae9-cf96568222c7.png">

**Comment by n8thangreen** [comment]
This looks to me like you haven't got a C compiler or at least R can't find it. Try installing again or checking the PATH.
