### ISSUE TITLE
Allowing for N nodes

### ISSUE THREAD

**Issue by RobertASmithBresMed** [n8thangreen/CEdecisiontree#9]
https://github.com/Health-Economics-in-R/CEdecisiontree/blob/2497646f7890ecbc12dad094c98e296e0806c853/R/dectree_expected_recursive.R#L47

Hi Nathan, 

Adapted your code (thanks) for a problem I was working on. Can't share the code but in short:

We needed more than 2 children per node, so basically replaced your L & R with a lapply:

```r
    # Loop though all children to find expected value (recursively)
    expected_value <- lapply(child, function(child_n){
      # Extract prob and if NA set to 0
      prob <- <insert code to get prob here, mine deviates from yours>
     
 if(is.na(prob)) prob <- 0
      
      # Calculate expected outcome of children (recursively)
      sub_out <- prob * dectree_expected_recursive(child_n, tree, dat, outcome)
 
      # return calculated value
      return(sub_out)
    })
    
    # Sum current node's outcome and the expected_value of the children
    out <- c_node + do.call(sum, expected_value)


```

Kind regards,

Rob

**Comment by n8thangreen** [comment]
Thanks. I had a go at this extension for the package and I think this is the simplest way I could do it.

https://github.com/Health-Economics-in-R/CEdecisiontree/commit/65dfa30daa524b69f73e96991870b03ec954152f
